/// Flutter icons NewzIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewzIcons
///      fonts:
///       - asset: fonts/NewzIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NewzIcons {
  NewzIcons._();

  static const _kFontFam = 'NewzIcons';
  static const String? _kFontPkg = null;

  static const IconData feed_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newz = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_outlined = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
